# Generated by Django 5.0.2 on 2024-02-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateField()),
                ('product_type', models.CharField(max_length=10)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
