# Generated by Django 5.0.1 on 2024-02-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('mobile', models.IntegerField(verbose_name='')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
